version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8181:8181
    depends_on:
      - mongo-db
  mongo-db:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - 'mongo-db:/data/db'
volumes:
  mongo-db:
