version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8181:8181
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - 'mongodb:/data/db'
volumes:
  mongodb:
